package EjerciciosPractica;

public class FormularioPrincipal_Grupo8 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioPrincipal_Grupo8.class.getName());

    public FormularioPrincipal_Grupo8() {
        initComponents();
        setTitle("Menú Principal – Grupo 8");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEjercicios = new javax.swing.JMenu();
        ItemEjercicio1 = new javax.swing.JMenuItem();
        ItemEjercicio2 = new javax.swing.JMenuItem();
        ItemEjercicio3 = new javax.swing.JMenuItem();
        ItemEjercicio4 = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Portada.png"))); // NOI18N

        menuEjercicios.setText("Ejercicios");

        ItemEjercicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Item.png"))); // NOI18N
        ItemEjercicio1.setText("Ejercicio 1");
        ItemEjercicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEjercicio1ActionPerformed(evt);
            }
        });
        menuEjercicios.add(ItemEjercicio1);

        ItemEjercicio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Item.png"))); // NOI18N
        ItemEjercicio2.setText("Ejercicio 2");
        ItemEjercicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEjercicio2ActionPerformed(evt);
            }
        });
        menuEjercicios.add(ItemEjercicio2);

        ItemEjercicio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Item.png"))); // NOI18N
        ItemEjercicio3.setText("Ejercicio 3");
        ItemEjercicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEjercicio3ActionPerformed(evt);
            }
        });
        menuEjercicios.add(ItemEjercicio3);

        ItemEjercicio4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Item.png"))); // NOI18N
        ItemEjercicio4.setText("Ejercicio 4");
        ItemEjercicio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEjercicio4ActionPerformed(evt);
            }
        });
        menuEjercicios.add(ItemEjercicio4);

        jMenuBar1.add(menuEjercicios);

        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuSalirMousePressed(evt);
            }
        });
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemEjercicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEjercicio3ActionPerformed
        CalculadoraconJComboBoxdeOperaciones_Grupo8 ejercicio3 = new CalculadoraconJComboBoxdeOperaciones_Grupo8();
        ejercicio3.setVisible(true);
    }//GEN-LAST:event_ItemEjercicio3ActionPerformed

    private void ItemEjercicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEjercicio1ActionPerformed
        FormulariodeSaludosPersonalizados_Grupo8 ejercicio1 = new FormulariodeSaludosPersonalizados_Grupo8();
        ejercicio1.setVisible(true);
    }//GEN-LAST:event_ItemEjercicio1ActionPerformed

    private void ItemEjercicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEjercicio2ActionPerformed
        CalculadoraBotonesGrupo8 ejercicio2 = new CalculadoraBotonesGrupo8();
        ejercicio2.setVisible(true);
    }//GEN-LAST:event_ItemEjercicio2ActionPerformed

    private void ItemEjercicio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEjercicio4ActionPerformed
        SelectordeColores_Grupo8 ejercicio4 = new SelectordeColores_Grupo8();
        ejercicio4.setVisible(true);
    }//GEN-LAST:event_ItemEjercicio4ActionPerformed

    private void menuSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMousePressed
        System.exit(0);
    }//GEN-LAST:event_menuSalirMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioPrincipal_Grupo8().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemEjercicio1;
    private javax.swing.JMenuItem ItemEjercicio2;
    private javax.swing.JMenuItem ItemEjercicio3;
    private javax.swing.JMenuItem ItemEjercicio4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuEjercicios;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
